trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: NodeTool@0
  displayName: "Install Node.js"
  inputs:
    versionSpec: "20.x"

- script: |
    cd app/catalog-service
    npm ci
  displayName: "Install Dependencies"

- script: |
    cd app/catalog-service
    npm test
  displayName: "Run Unit Tests"

- task: PublishTestResults@2
  displayName: "Publish Test Results"
  inputs:
    testResultsFormat: "JUnit"
    testResultsFiles: "app/catalog-service/junit.xml"
    failTaskOnFailedTests: true